### ISSUE TITLE
Node EFI image doesn't boot on some real hardware

### ISSUE THREAD

**Issue by q3k** [monogon-dev/monogon#102]
@msgctl and @lorenz have been doing some troubleshooting of Metropolis on real hardware.

The symptoms are that after the firmware boots into the image, we get a blank screen. This might be our EFI stub, this might be the Linux EFI stub we then launch, it might be some Linux configuration. It probably doesn't come back after calling `ExitBootServices`.

@lorenz has just got some hardware to debug this (LPC bus sniffing for outb() tombstone debugging)

**Comment by lorenz** [comment]
At least on my hardware platform (an AOpen i67QMX-DV) our kernel boots just fine, except we don't have any output. We need to configure the kernel console for dual-output on the EFI framebuffer and serial.

**Comment by lorenz** [comment]
We think the original issue is now fixed. The following issues contributed to this:
a) We didn't have EFI console driver so we had no output
b) The installer failed because the USB drive could not be found for lack of a USB driver
c) The installer actually needs to wait for block devices because for example USB devices might show up late

These are all fixed as of current main.

**Comment by q3k** [comment]
With the above issues fixed, we can now boot on an HP Z420 workstation (which was one of the platforms that didn't work before).

**Comment by lorenz** [comment]
It now works on all machines it originally didn't so closing this. We can open new platform-specific issues if they aries.
