### ISSUE TITLE
Enable hermetic sandbox

### ISSUE THREAD

**Issue by leoluk** [monogon-dev/monogon#174]
With the sandboxroot, we should now - in theory - be able to turn on `--experimental_use_hermetic_linux_sandbox`, which starts with an empty mount namespace instead of mounting the sandbox dirs on top of the host directories.

This is currently thwarted by a rules_go bug:

https://github.com/bazelbuild/rules_go/issues/1910

**Comment by q3k** [comment]
I was getting `go: cannot find GOROOT directory: /usr/local/go` and I debugged a bit further.

Turns out this is because Go needs a GOROOT, and it either runtime find one, or falls back to /usr/local/go. The runtime detection relies on reading /proc/self/exe, and in our experimental hermetic builds we simply weren't mounting /proc.

Adding `--sandbox_add_mount_pair=/proc:/proc` gets us further on this.
