### ISSUE TITLE
metropolis: don't run DNS resolver on :53

### ISSUE THREAD

**Issue by q3k** [monogon-dev/monogon#217]
Currently we're running CoreDNS on all interfaces, including the public one, and we serve all traffic there, including `ANY google.com`. This isn't great.

Either ACL this and ideally don't run it on the public interface.

**Comment by lorenz** [comment]
This was mostly working, but sadly flaky. CoreDNS's reloads are broken and end up in a state where it does no longer serve requests because the listener FDs got messed up. Me and @fionera were trying to steal their plugins, which does somewhat work, but they expect data in contexts and some plugins are not properly reloadable themselves so this is not a shot-term solution. I decided to work around this by hardcoding the listeners for the time being.
