### ISSUE TITLE
Time synchronization

### ISSUE THREAD

**Issue by leoluk** [monogon-dev/monogon#3]
(originally reported in T560)

There appears to be a distinct lack of full NTP implementations in memory-safe languages, and plain NTP is prone to various man-in-the-middle attacks.

We may get away with something like Roughtime for most workloads.

For workloads like CockroachDB or others that require very precise time, we may have to run a fully-featured NTP client like chrony or even a PTP client in a sandbox.

**Comment by q3k** [comment]
The big question here is what sort of time system do we even use. Standard NTP UTC? Smeared NTP UTC? PTP? 

After a quick internal discussion, the consensus seems to be as follows:

 - We very much don't want to support everything under the sun, as that will come to bite us later on.
 - If we're picking one time system, we probably want to use smeared NTP, at least for Metropolis code.
 - For user workloads, we might also then look into time namespaces? So that we can let users override the time system if really needed.

But we'll come back to the discussion when we actually start designing and implementing it.

**Comment by lorenz** [comment]
MVP implementation in e306d780504ae3ddfad3eb852c7adc5ec9757d89
