### ISSUE TITLE
metropolis: TestABUpdateSequenceKexec timeouts

### ISSUE THREAD

**Issue by fionera** [monogon-dev/monogon#303]
It happens every now and then that the AB update tests are timing out.
```
--- FAIL: TestABUpdateSequenceKexec (30.60s)
    e2e_test.go:67: qemu: qemu-system-x86_64: warning: This family of AMD CPU doesn't support hyperthreading(2)
    e2e_test.go:67: qemu: Please configure -smp options properly or try enabling topoext feature.
    e2e_test.go:67: qemu: qemu-system-x86_64: -fw_cfg name=use_kexec,string=1: warning: externally provided fw_cfg item names should be prefixed with "opt/"
    e2e_test.go:322: Waiting for TestOS variant X launch timed out
FAIL
```

**Comment by lorenz** [comment]
These tests take ~20s on an unloaded machine (mostly due to EFI boto overhead), the test timeout was set a bit too close as they also do IO which can be congested. https://review.monogon.dev/c/monogon/+/3206 changed the timeout to 60s and https://review.monogon.dev/c/monogon/+/3209 shaved a few seconds off the boot overhead. Basically the only actionable thing left here would be to improve the test to not do any IO, but that is a more general issues.
