### ISSUE TITLE
Escrow Kubernetes Credentials

### ISSUE THREAD

**Issue by q3k** [monogon-dev/monogon#90]
We currently don't have a way to get Kubernetes credentials without using the Debug Service.

We should add an RPC endpoint that peforms yet another credential escrow: from cluster manager/client credentials to Kubernetes credentials.

Or, we should get kube-apiserver to accept Metropolis credentials? I think we don't want to do that thought, because the apiserver has no CRL functionality... To investigate.

**Comment by lorenz** [comment]
Getting kube-apiserver to directly accept Metropolis credentials seems unwise because it doesn't really have a revocation story.
There is an option however to use a client [credentials plugin](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins) together with an [authenticating proxy](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#authenticating-proxy) which should get us there without needing another escrow mechanism.

@q3k What do you think?

**Comment by leoluk** [comment]
> Getting kube-apiserver to directly accept Metropolis credentials seems unwise because it doesn't really have a revocation story.

Or could we perhaps add a lightweight TLS inspecting proxy that checks revocation? That way we could avoid the client side plugin (if we even care about that).

**Comment by lorenz** [comment]
Yeah, but we'd still need something to provision the credentials into K8s, so we might as well have that plugin. I have a prototype with it, it's super short (~50 LOC).

**Comment by leoluk** [comment]
Ah - thought you were suggesting to use the same CA/certificates. Makes sense!

**Comment by lorenz** [comment]
Working draft now up at
https://review.monogon.dev/c/monogon/+/508
https://review.monogon.dev/c/monogon/+/509

Automatic kubeconfig generation not yet implemented

**Comment by lorenz** [comment]
Main feature landed in cc078df, I'm going to close this and track automatic kubeconfig configuration as part of metroctl
